<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Customers extends \Customers implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getCustomerId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["customerId"];
        }
        $this->__load();
        return parent::getCustomerId();
    }

    public function setCustomerFirstName($customerFirstName)
    {
        $this->__load();
        return parent::setCustomerFirstName($customerFirstName);
    }

    public function getCustomerFirstName()
    {
        $this->__load();
        return parent::getCustomerFirstName();
    }

    public function setCustomerMiddleName($customerMiddleName)
    {
        $this->__load();
        return parent::setCustomerMiddleName($customerMiddleName);
    }

    public function getCustomerMiddleName()
    {
        $this->__load();
        return parent::getCustomerMiddleName();
    }

    public function setCustomerLastName($customerLastName)
    {
        $this->__load();
        return parent::setCustomerLastName($customerLastName);
    }

    public function getCustomerLastName()
    {
        $this->__load();
        return parent::getCustomerLastName();
    }

    public function setGender($gender)
    {
        $this->__load();
        return parent::setGender($gender);
    }

    public function getGender()
    {
        $this->__load();
        return parent::getGender();
    }

    public function setEmailAddress($emailAddress)
    {
        $this->__load();
        return parent::setEmailAddress($emailAddress);
    }

    public function getEmailAddress()
    {
        $this->__load();
        return parent::getEmailAddress();
    }

    public function setLoginName($loginName)
    {
        $this->__load();
        return parent::setLoginName($loginName);
    }

    public function getLoginName()
    {
        $this->__load();
        return parent::getLoginName();
    }

    public function setLoginPassword($loginPassword)
    {
        $this->__load();
        return parent::setLoginPassword($loginPassword);
    }

    public function getLoginPassword()
    {
        $this->__load();
        return parent::getLoginPassword();
    }

    public function setPhoneNumber($phoneNumber)
    {
        $this->__load();
        return parent::setPhoneNumber($phoneNumber);
    }

    public function getPhoneNumber()
    {
        $this->__load();
        return parent::getPhoneNumber();
    }

    public function setStreet($street)
    {
        $this->__load();
        return parent::setStreet($street);
    }

    public function getStreet()
    {
        $this->__load();
        return parent::getStreet();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setZipCode($zipCode)
    {
        $this->__load();
        return parent::setZipCode($zipCode);
    }

    public function getZipCode()
    {
        $this->__load();
        return parent::getZipCode();
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function setOtherDetails($otherDetails)
    {
        $this->__load();
        return parent::setOtherDetails($otherDetails);
    }

    public function getOtherDetails()
    {
        $this->__load();
        return parent::getOtherDetails();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'customerId', 'customerFirstName', 'customerMiddleName', 'customerLastName', 'gender', 'emailAddress', 'loginName', 'loginPassword', 'phoneNumber', 'street', 'city', 'zipCode', 'country', 'otherDetails');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}