<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ProductTypes extends \ProductTypes implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getProductTypeCode()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["productTypeCode"];
        }
        $this->__load();
        return parent::getProductTypeCode();
    }

    public function setProductTypeDescription($productTypeDescription)
    {
        $this->__load();
        return parent::setProductTypeDescription($productTypeDescription);
    }

    public function getProductTypeDescription()
    {
        $this->__load();
        return parent::getProductTypeDescription();
    }

    public function setVatRating($vatRating)
    {
        $this->__load();
        return parent::setVatRating($vatRating);
    }

    public function getVatRating()
    {
        $this->__load();
        return parent::getVatRating();
    }

    public function setParentProductTypeCode(\ProductTypes $parentProductTypeCode = NULL)
    {
        $this->__load();
        return parent::setParentProductTypeCode($parentProductTypeCode);
    }

    public function getParentProductTypeCode()
    {
        $this->__load();
        return parent::getParentProductTypeCode();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'productTypeCode', 'productTypeDescription', 'vatRating', 'parentProductTypeCode');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}